### ISSUE TITLE
Outputs Example

### ISSUE THREAD

**Issue by ProbablePrime** [serverless/site#120]
On https://serverless.com/framework/docs/providers/aws/guide/serverless.yml the format for the example output is incorrect.

It reads:
```
  Outputs:
    UsersTableArn:
      Description: The ARN for the User's Table
      Value:
        "Fn::GetAtt": [ usersTable, Arn ]
      Export: ${self:service}:${opt:stage}:UsersTableArn
```

But based on the [documentation for cloudformation outputs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) this should be:

```
  Outputs:
    UsersTableArn:
      Description: The ARN for the User's Table
      Value:
        "Fn::GetAtt": [ usersTable, Arn ]
      Export: 
        Name: ${self:service}:${opt:stage}:UsersTableArn
```
Using this as an example will lead to:
`The CloudFormation template is invalid: Template format error: Output UsersTableArn is malformed. The Export field of every Outputs member must be a Map.`
