### ISSUE TITLE
Function name in example supposed to be "usersDelete"

### ISSUE THREAD

**Issue by yudho** [serverless/site#47]
In this page https://serverless.com/framework/docs/providers/aws/guide/services/
under serverless.yml section, the code example is supposed to be
````
functions:
  usersCreate: # A Function
    events: # The Events that trigger this Function
      - http: post users/create
  usersDelete: # A Function
    events:  # The Events that trigger this Function
      - http: delete users/delete
````

instead of 

````functions:
  usersCreate: # A Function
    events: # The Events that trigger this Function
      - http: post users/create
  usersCreate: # A Function
    events:  # The Events that trigger this Function
      - http: delete users/delete
````

Attached screenshot
![screen shot 2016-10-26 at 8 21 10 am](https://cloud.githubusercontent.com/assets/1488376/19708969/6419072a-9b55-11e6-9156-a25f5024b317.png)
