### ISSUE TITLE
feat(docs/functions): Add description field

### ISSUE THREAD

**Issue by goncaloneves** [serverless/site#50]
Nowhere to be found lambda "description" field in the docs.
Just tested version 1.0.3 and field is working as it was in 0.5.x.

**serverless.yml**
```
functions:
  hello:
    name: hello
    description: This is the field that is missing in the docs
    handler: index.handler
```

Could be added here:
https://serverless.com/framework/docs/providers/aws/guide/functions/
